- name: Populate hosts file
  hosts: cluster
  become: true
  become_user: root
  become_method: sudo
  tasks:

  - name: add hostname to /etc/hosts
    vars:
      comment: '# added by ansible'
    lineinfile:
      dest: /etc/hosts
      regexp: "127[.]0[.]0[.]1.*"
      line: "127.0.0.1 localhost.localdomain localhost {{ ansible_hostname }} {{ comment }}"
      state: present
      backup: yes

  - name: add IP address to the hosts file
    vars:
      comment: '# added by ansible'
    lineinfile:
      dest: /etc/hosts
      regexp: ".* {{ item }} {{ comment }}"
      line: "{{ hostvars[item]['ansible_env'].SSH_CONNECTION.split(' ')[2] }} {{ item }} {{ comment }}"
      state: present
      backup: yes
    when: ansible_hostname != item
    loop: "{{ query('inventory_hostnames', 'all') }}"
